import { OrderIntent } from '../execution/order_router';

/**
 * Signal generated by a strategy
 */
export interface Signal {
  signalId: string;
  strategyId: string;
  symbol: string;
  side: 'buy' | 'sell';
  strength: number; // 0-1, confidence level
  price: number; // Price at time of signal
  reason: string; // Why this signal was generated
  features?: Record<string, any>; // Additional data (indicators, etc.)
  timestamp: Date;
}

/**
 * Strategy configuration
 */
export interface StrategyConfig {
  strategyId: string;
  name: string;
  version: string;
  enabled: boolean;
  params: Record<string, any>;
  symbols: string[]; // Which symbols to trade
  schedule?: string; // Cron expression (e.g., "*/5 * * * *" for every 5 min)
}

/**
 * Market data for strategy evaluation
 */
export interface MarketData {
  symbol: string;
  timestamp: Date;
  open: number;
  high: number;
  low: number;
  close: number;
  volume: number;
}

/**
 * Base strategy interface - all strategies must implement this
 */
export interface IStrategy {
  /**
   * Unique strategy identifier
   */
  getId(): string;

  /**
   * Strategy name
   */
  getName(): string;

  /**
   * Strategy version
   */
  getVersion(): string;

  /**
   * Get strategy configuration
   */
  getConfig(): StrategyConfig;

  /**
   * Initialize strategy (called once on startup)
   */
  initialize(): Promise<void>;

  /**
   * Generate trading signals
   * @param marketData Recent market data for symbols
   * @returns Array of signals (can be empty)
   */
  generateSignals(marketData: Map<string, MarketData[]>): Promise<Signal[]>;

  /**
   * Convert signal to order intent
   * @param signal The signal to execute
   * @returns Order intent ready for risk checks
   */
  signalToIntent(signal: Signal): Promise<OrderIntent>;

  /**
   * Cleanup (called on shutdown)
   */
  cleanup(): Promise<void>;
}

/**
 * Strategy metadata for registry
 */
export interface StrategyMetadata {
  id: string;
  name: string;
  version: string;
  description: string;
  author: string;
  params: {
    name: string;
    type: 'number' | 'string' | 'boolean' | 'array';
    default: any;
    description: string;
  }[];
}
