-- ============================================
-- OpenClaw Trader - Initial Schema
-- Version: 001
-- Description: Core trading tables with immutable audit trail
-- ============================================

-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ============================================
-- STRATEGIES & SIGNALS
-- ============================================

-- Strategy definitions
CREATE TABLE trd_strategy (
  strategy_id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  name VARCHAR(100) NOT NULL UNIQUE,
  version VARCHAR(20) NOT NULL,
  enabled BOOLEAN NOT NULL DEFAULT false,
  params_json JSONB NOT NULL DEFAULT '{}',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_strategy_enabled ON trd_strategy(enabled);
COMMENT ON TABLE trd_strategy IS 'Trading strategy definitions';

-- Trading signals (what strategy detected)
CREATE TABLE trd_signal (
  signal_id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  strategy_id UUID NOT NULL REFERENCES trd_strategy(strategy_id),
  symbol VARCHAR(20) NOT NULL,
  side VARCHAR(10) NOT NULL CHECK (side IN ('buy', 'sell')),
  confidence DECIMAL(5,4) CHECK (confidence >= 0 AND confidence <= 1),
  signal_ts TIMESTAMPTZ NOT NULL,
  features_json JSONB DEFAULT '{}',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_signal_strategy ON trd_signal(strategy_id, signal_ts DESC);
CREATE INDEX idx_signal_symbol ON trd_signal(symbol, signal_ts DESC);
CREATE INDEX idx_signal_ts ON trd_signal(signal_ts DESC);
COMMENT ON TABLE trd_signal IS 'Trading signals generated by strategies';

-- ============================================
-- ORDER FLOW (Intent → Risk → Order → Fill)
-- ============================================

-- Order intent (what strategy WANTED to do)
CREATE TABLE trd_order_intent (
  intent_id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  signal_id UUID REFERENCES trd_signal(signal_id),
  strategy_id UUID NOT NULL REFERENCES trd_strategy(strategy_id),
  symbol VARCHAR(20) NOT NULL,
  side VARCHAR(10) NOT NULL CHECK (side IN ('buy', 'sell')),
  qty DECIMAL(18,8) NOT NULL CHECK (qty > 0),
  order_type VARCHAR(20) NOT NULL CHECK (order_type IN ('market', 'limit', 'stop', 'stop_limit')),
  limit_price DECIMAL(18,8),
  time_in_force VARCHAR(10) NOT NULL DEFAULT 'day' CHECK (time_in_force IN ('day', 'gtc', 'ioc', 'fok')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_intent_strategy ON trd_order_intent(strategy_id, created_at DESC);
CREATE INDEX idx_intent_symbol ON trd_order_intent(symbol, created_at DESC);
CREATE INDEX idx_intent_created ON trd_order_intent(created_at DESC);
COMMENT ON TABLE trd_order_intent IS 'Order intents before risk checks (immutable)';

-- Risk check results (BEFORE order submission)
CREATE TABLE trd_risk_check (
  check_id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  intent_id UUID NOT NULL REFERENCES trd_order_intent(intent_id),
  passed BOOLEAN NOT NULL,
  fail_reason TEXT,
  limits_snapshot_json JSONB NOT NULL, -- Capture all limits at check time
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_risk_check_intent ON trd_risk_check(intent_id);
CREATE INDEX idx_risk_check_failed ON trd_risk_check(passed, created_at DESC) WHERE NOT passed;
CREATE INDEX idx_risk_check_created ON trd_risk_check(created_at DESC);
COMMENT ON TABLE trd_risk_check IS 'Pre-trade risk check results (immutable)';

-- Actual orders sent to broker
CREATE TABLE trd_order (
  order_id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  intent_id UUID NOT NULL REFERENCES trd_order_intent(intent_id),
  broker_order_id VARCHAR(100) UNIQUE,
  status VARCHAR(20) NOT NULL CHECK (status IN ('pending', 'submitted', 'filled', 'partial', 'cancelled', 'rejected')),
  submitted_at TIMESTAMPTZ,
  last_update_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_order_intent ON trd_order(intent_id);
CREATE INDEX idx_order_broker ON trd_order(broker_order_id);
CREATE INDEX idx_order_status ON trd_order(status, submitted_at DESC);
CREATE INDEX idx_order_submitted ON trd_order(submitted_at DESC);
COMMENT ON TABLE trd_order IS 'Orders sent to broker';

-- Order fills (from broker)
CREATE TABLE trd_fill (
  fill_id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  order_id UUID NOT NULL REFERENCES trd_order(order_id),
  price DECIMAL(18,8) NOT NULL,
  qty DECIMAL(18,8) NOT NULL CHECK (qty > 0),
  fee DECIMAL(18,8) NOT NULL DEFAULT 0,
  fill_ts TIMESTAMPTZ NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_fill_order ON trd_fill(order_id);
CREATE INDEX idx_fill_ts ON trd_fill(fill_ts DESC);
COMMENT ON TABLE trd_fill IS 'Order fills from broker (immutable)';

-- ============================================
-- PORTFOLIO & P&L
-- ============================================

-- Position snapshots (time-series)
CREATE TABLE trd_position_snapshot (
  snap_id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  symbol VARCHAR(20) NOT NULL,
  qty DECIMAL(18,8) NOT NULL,
  avg_price DECIMAL(18,8) NOT NULL,
  market_price DECIMAL(18,8) NOT NULL,
  unrealized_pnl DECIMAL(18,2) NOT NULL,
  ts TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_position_snapshot_symbol ON trd_position_snapshot(symbol, ts DESC);
CREATE INDEX idx_position_snapshot_ts ON trd_position_snapshot(ts DESC);
COMMENT ON TABLE trd_position_snapshot IS 'Position snapshots over time';

-- Daily P&L rollup
CREATE TABLE trd_pnl_day (
  date DATE PRIMARY KEY,
  realized_pnl DECIMAL(18,2) NOT NULL DEFAULT 0,
  unrealized_pnl DECIMAL(18,2) NOT NULL DEFAULT 0,
  fees DECIMAL(18,2) NOT NULL DEFAULT 0,
  net_pnl DECIMAL(18,2) GENERATED ALWAYS AS (realized_pnl + unrealized_pnl - fees) STORED,
  trade_count INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_pnl_day_date ON trd_pnl_day(date DESC);
COMMENT ON TABLE trd_pnl_day IS 'Daily P&L summary';

-- ============================================
-- SAFETY & MONITORING
-- ============================================

-- Kill switch events
CREATE TABLE trd_kill_switch_event (
  event_id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  trigger VARCHAR(50) NOT NULL CHECK (trigger IN ('manual', 'breach', 'heartbeat_miss')),
  mode VARCHAR(10) NOT NULL CHECK (mode IN ('soft', 'hard')),
  reason TEXT NOT NULL,
  actor VARCHAR(100), -- user_id or 'system'
  ts TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_kill_switch_ts ON trd_kill_switch_event(ts DESC);
CREATE INDEX idx_kill_switch_trigger ON trd_kill_switch_event(trigger);
COMMENT ON TABLE trd_kill_switch_event IS 'Kill switch trigger events (immutable)';

-- Risk limit definitions
CREATE TABLE trd_risk_limit (
  limit_id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  limit_type VARCHAR(50) NOT NULL UNIQUE,
  value DECIMAL(18,2) NOT NULL,
  unit VARCHAR(20) NOT NULL CHECK (unit IN ('USD', 'percent', 'count', 'bps')),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_by VARCHAR(100)
);

COMMENT ON TABLE trd_risk_limit IS 'Risk limit configuration';

-- Audit log (immutable)
CREATE TABLE trd_audit_log (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  actor VARCHAR(100) NOT NULL, -- user_id or 'system'
  action VARCHAR(50) NOT NULL,
  resource VARCHAR(100) NOT NULL,
  diff_json JSONB,
  ts TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_audit_log_actor ON trd_audit_log(actor, ts DESC);
CREATE INDEX idx_audit_log_resource ON trd_audit_log(resource, ts DESC);
CREATE INDEX idx_audit_log_ts ON trd_audit_log(ts DESC);
COMMENT ON TABLE trd_audit_log IS 'Immutable audit trail of all actions';

-- ============================================
-- OPERATIONAL
-- ============================================

-- Trading runs
CREATE TABLE trd_run (
  run_id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  mode VARCHAR(10) NOT NULL CHECK (mode IN ('paper', 'live')),
  status VARCHAR(20) NOT NULL CHECK (status IN ('running', 'stopped', 'error')),
  started_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  ended_at TIMESTAMPTZ,
  error TEXT
);

CREATE INDEX idx_run_started ON trd_run(started_at DESC);
CREATE INDEX idx_run_status ON trd_run(status);
COMMENT ON TABLE trd_run IS 'Trading run history';

-- Service heartbeat
CREATE TABLE trd_heartbeat (
  service VARCHAR(50) PRIMARY KEY,
  last_seen_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  status VARCHAR(20) NOT NULL DEFAULT 'healthy' CHECK (status IN ('healthy', 'degraded', 'unhealthy'))
);

COMMENT ON TABLE trd_heartbeat IS 'Service health status';

-- Kill switch state (singleton table)
CREATE TABLE trd_kill_switch_state (
  id INTEGER PRIMARY KEY DEFAULT 1 CHECK (id = 1), -- Ensures only one row
  status VARCHAR(20) NOT NULL DEFAULT 'armed' CHECK (status IN ('armed', 'triggered')),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_by VARCHAR(100)
);

-- Insert initial state
INSERT INTO trd_kill_switch_state (status) VALUES ('armed');
COMMENT ON TABLE trd_kill_switch_state IS 'Current kill switch state (singleton)';

-- ============================================
-- INITIAL DATA
-- ============================================

-- Insert default risk limits
INSERT INTO trd_risk_limit (limit_type, value, unit) VALUES
  ('max_daily_loss', 500.00, 'USD'),
  ('max_position_usd', 2000.00, 'USD'),
  ('max_gross_exposure_usd', 5000.00, 'USD'),
  ('max_trades_per_day', 10, 'count'),
  ('max_order_slippage_bps', 50, 'bps');

-- Insert initial heartbeat
INSERT INTO trd_heartbeat (service, status) VALUES
  ('trader-service', 'healthy');

-- ============================================
-- FUNCTIONS & TRIGGERS
-- ============================================

-- Update updated_at timestamp automatically
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ language 'plpgsql';

-- Apply to tables with updated_at
CREATE TRIGGER update_trd_strategy_updated_at BEFORE UPDATE ON trd_strategy
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_trd_pnl_day_updated_at BEFORE UPDATE ON trd_pnl_day
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- ============================================
-- GRANTS (Adjust for your user)
-- ============================================

-- Grant permissions to trader_user
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO trader_user;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO trader_user;

-- ============================================
-- VERIFICATION
-- ============================================

-- Verify table count
DO $$
DECLARE
  table_count INTEGER;
BEGIN
  SELECT COUNT(*) INTO table_count
  FROM information_schema.tables
  WHERE table_schema = 'public' AND table_type = 'BASE TABLE';

  RAISE NOTICE 'Created % tables', table_count;
END $$;

-- List all tables
SELECT tablename FROM pg_tables WHERE schemaname = 'public' ORDER BY tablename;
