/**
 * @file contentGuard.js
 * @description Content safety filter for outreach emails and social posts.
 *
 * Scans LLM-generated content for banned phrases, competitor mentions,
 * false claims, and compliance violations before they reach draft status.
 *
 * Usage:
 *   const { checkContent } = require('./contentGuard');
 *   const result = checkContent(emailBody, emailSubject);
 *   if (!result.safe) { console.warn('Flagged:', result.flags); }
 */

// ══════════════════════════════════════════════════════════════
// BANNED PHRASE LISTS
// ══════════════════════════════════════════════════════════════

/** Competitor names — never mention in outreach */
const COMPETITOR_NAMES = [
  'sage 300', 'sage intacct', 'sage 100', 'viewpoint', 'vista by viewpoint',
  'procore', 'foundation software', 'computerease', 'jonas construction',
  'acumatica', 'corecon', 'buildertrend', 'cmic', 'dexter chaney',
  'timberline', 'hh2', 'b2w', 'quickbooks', 'xero', 'netsuite',
];

/** False or exaggerated claims — LLMs love to fabricate these */
const FALSE_CLAIM_PATTERNS = [
  /guarantee[ds]?\s+(savings?|results?|roi|return)/i,
  /100%\s+(satisfaction|guaranteed|success|accurate)/i,
  /\b(award[- ]winning|#1|number one|best in class|industry[- ]leading)\b/i,
  /save[ds]?\s+\$[\d,]+/i,                    // "save $50,000" — specific dollar claims
  /\b(proven|certified|accredited)\b.*\b(results?|methodology|system)\b/i,
  /\b(thousands|hundreds)\s+of\s+(companies|clients|customers)\b/i,  // inflated client count
];

/** Compliance violations */
const COMPLIANCE_PATTERNS = [
  /\b(unsubscribe|opt[- ]?out|remove me)\b/i, // Agent shouldn't write unsubscribe language — that's in the email footer
  /\b(confidential|privileged|not intended)\b/i, // Legal disclaimers generated by LLM
  /\bfree\s+(money|cash|grant)\b/i,           // Misleading financial language (especially for HOA)
  /\b(no risk|risk[- ]?free|zero risk)\b/i,   // Can't promise no risk in financial context
];

/** Spam trigger words — reduce deliverability */
const SPAM_TRIGGERS = [
  /\b(act now|limited time|don'?t miss|hurry|urgent offer)\b/i,
  /\b(click (here|below|now)|buy now|order now)\b/i,
  /\b(congratulations|you'?ve been selected|you'?re a winner)\b/i,
  /!!+/,                                       // Multiple exclamation marks
  /\bFREE\b/,                                  // All-caps FREE
];

/** Tone violations — Jake persona should never sound like this */
const TONE_VIOLATIONS = [
  /\b(dear sir|dear madam|to whom it may concern)\b/i,
  /\b(humbly|respectfully submit|beg to differ)\b/i,
  /\b(synergy|leverage|paradigm|disrupt|move the needle)\b/i,
  /\b(circle back|ping me|touch base|low[- ]hanging fruit)\b/i,
];

// ══════════════════════════════════════════════════════════════
// CHECK FUNCTION
// ══════════════════════════════════════════════════════════════

/**
 * Check content for banned phrases, false claims, and compliance issues.
 *
 * @param {string} body - Email body text
 * @param {string} [subject] - Email subject line (optional)
 * @returns {{ safe: boolean, flags: Array<{type: string, match: string, severity: string}> }}
 */
function checkContent(body, subject = '') {
  const flags = [];
  const fullText = `${subject} ${body}`.toLowerCase();

  // Competitor mentions
  for (const name of COMPETITOR_NAMES) {
    if (fullText.includes(name.toLowerCase())) {
      flags.push({ type: 'competitor_mention', match: name, severity: 'high' });
    }
  }

  // False claims
  for (const pattern of FALSE_CLAIM_PATTERNS) {
    const match = fullText.match(pattern);
    if (match) {
      flags.push({ type: 'false_claim', match: match[0], severity: 'high' });
    }
  }

  // Compliance
  for (const pattern of COMPLIANCE_PATTERNS) {
    const match = fullText.match(pattern);
    if (match) {
      flags.push({ type: 'compliance', match: match[0], severity: 'medium' });
    }
  }

  // Spam triggers
  for (const pattern of SPAM_TRIGGERS) {
    const match = fullText.match(pattern);
    if (match) {
      flags.push({ type: 'spam_trigger', match: match[0], severity: 'low' });
    }
  }

  // Tone violations
  for (const pattern of TONE_VIOLATIONS) {
    const match = fullText.match(pattern);
    if (match) {
      flags.push({ type: 'tone_violation', match: match[0], severity: 'low' });
    }
  }

  // Length check — outreach emails should be 100-300 words
  const wordCount = body.split(/\s+/).filter(Boolean).length;
  if (wordCount > 500) {
    flags.push({ type: 'too_long', match: `${wordCount} words`, severity: 'medium' });
  }
  if (wordCount < 30) {
    flags.push({ type: 'too_short', match: `${wordCount} words`, severity: 'medium' });
  }

  const hasHighSeverity = flags.some(f => f.severity === 'high');

  return {
    safe: !hasHighSeverity,
    flagCount: flags.length,
    flags,
    wordCount,
  };
}

module.exports = { checkContent, COMPETITOR_NAMES, FALSE_CLAIM_PATTERNS };
